name: Vault-Agent HCL to Windows Server

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    #1st command is to copy the updated ./vault-agent.hcl File from Github to Windows server using SSH
    #2nd command is to stop the Vault Agent Service
    #3rd command is to start the Vault Agent Service
    # In this case To start and stop the Vault Agent Service so that it can update the changes of generating secrets to txt file
    - name: Update HCL file
      run: |
        sshpass -p ${{ secrets.WINDOWS_PASSWORD }} scp ./vault-agent.hcl Administrator@192.168.100.160:/C:/vault-agent
  
  
  
  
  
  
  
  
  
  
  
  
  # sshpass -p ${{ secrets.WINDOWS_PASSWORD }} ssh Administrator@192.168.100.160 'net stop VaultAgent'
   #     sshpass -p ${{ secrets.WINDOWS_PASSWORD }} ssh Administrator@192.168.100.160 'net start VaultAgent'

